### ISSUE TITLE
[REQUEST]

### ISSUE THREAD

**Issue by susitucker** [nikkisaurus/farmingbar#37]
I would like to request an enhancement to the addon in relation to user profiles. I have tried to execute this with the existing setup, but it doesn't seem to work. 

I would like to have a profile for a certain combination of professions. So if I have an herbalist and a skinner, I would like to keep track of each of the respective items they collect, one bar for each profession for each expansion. So I'd have about 18-20 bars at this point. I would like to save this collection of bars as a profile so that one of my alts, who's also an herbalist and a skinner, can simply load the saved profile and have all the bars created and ready to display as needed. 

I have tried this already, but it doesn't seem to work. If there is something special I need to do, I'm all ears.

I love this addon so much, and I'm so grateful that you've created it. I hope what I've suggested makes sense and wouldn't be too much trouble to implement.

Thank you!!

**Comment by niketa-wow** [comment]
Hi. Sorry it's taken so long for a response. I started writing one out at work, but got busy and then forgot. lol

Anyway, the current iteration of profiles doesn't exactly work the way you'd expect. It controls only style settings. This has been fixed in the alpha version of the game. However, even within the alpha, only bars are saved, not objectives on them. There are templates that you can load for the bars, but you would need to do this for each bar on each toon. There should be presets already for each expansion's basic profession items that you can already load. Otherwise, save your bar as a new template, which you can load onto others.

I may add an option in the future to save objective information as well, but the alpha has been a long time project and I can't guarantee it'll happen soon. Thanks for the feedback!

**Comment by susitucker** [comment]
Hi. Thank you for your reply! I appreciate your taking the time. I am fine with how the addon works, believe me...it is so nice to have, especially how flexible it is overall. I also appreciate the work you put into making this addon! Thanks again. :)

**Comment by nikkisaurus** [comment]
Profiles have been revamped in the latest beta release.
