### ISSUE TITLE
[Bug]: Farming Bar is not including the bank

### ISSUE THREAD

**Issue by Neutralis525** [nikkisaurus/FarmingBar#57]
### Interface Version

10.0.5

### AddOn Version

10.0.5

### Have you replicated this error without any other addons loaded?

Yes

### What steps did you take leading up to this issue?

Farming Bar doesn't include items from the bank (Bank option is checked) until I open the bank.

**Comment by nikkisaurus** [comment]
Which items are you having the issue with?
Are you having any lua errors?
Does the issue happen every reload or only when relogging?

**Comment by Neutralis525** [comment]
I'm having issues with the Draenic Seeds and the stones you get from mining. I like to keep them in my bank. I included the bank but it sometimes doesn't register until I get to the bank. Otherwise it works great! I love how it shows everything across all your characters! Thank you for making these!

Sent from my U.S.Cellular© Smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by nikkisaurus** [comment]
I'm sorry it's taken so long to address this issue. I have a few more questions, if you wouldn't mind answering.

1. Are the items in the reagent bank or regular bank?
2. Are you using DataStore (I'm assuming yes, since you mention the cross character counts, but just need to make sure).
3. Has this problem happened with all items in your bank, or just the Draenic Seeds and stones?
4. Once you open your bank and it includes them, do you need to repeat this at any point, such as after a reload or relog? Or is it only after initially creating the objective?

Thanks!

**Comment by nikkisaurus** [comment]
I am closing this issue because I never got a response, and I believe this error is the same as #64, which I will have a fix for this week.
